name: CI/CD Pipeline Backend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-deploy:
    name: Compilación, Pruebas y Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código fuente
        uses: actions/checkout@v4

      # PASO DE DEPURE: Esto nos dirá si la carpeta es 'backend' o 'Backend'
      - name: Comprobar estructura de carpetas
        run: ls -R

      - name: 2. Configurar entorno Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Ajustado a minúsculas para coincidir con tu carpeta real
          cache-dependency-path: 'backend/package-lock.json' 

      - name: 3. Instalación de dependencias
        run: npm ci
        working-directory: ./backend

      - name: 4. Ejecución de Pruebas y Cobertura (CI)
        run: npm run test:coverage
        working-directory: ./backend
        env:
          NODE_ENV: test
          SESSION_SECRET: "test_secret"
          JWT_SECRET: "test_jwt_secret"
          CLIENT_URL: "http://localhost:5173"

      - name: 5. Despliegue en Render (CD)
        if: success() && github.event_name == 'push'
        run: |
          curl -s "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo "Pipeline completado con éxito."
